Fix regarding validation of project in Sonar

diff --git a/.github/workflows/pipeline-ic.yml b/.github/workflows/pipeline-ic.yml
--- a/.github/workflows/pipeline-ic.yml
+++ b/.github/workflows/pipeline-ic.yml
@@ -19,19 +19,19 @@ jobs:
         id: validate-project-sonar
         run: |
           curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'organization=curso-seguridad-usach' -d 'project=${{ github.event.repository.name }}' -d 'visibility=public' 
-          if [ $? -eq 0 ]; then
+          if [ $? -ne 0 ]; then
+            echo "Proyecto ya creado en Sonarcloud o error detectado durante la creación"
+          else
             echo "Proyecto creado exitosamente en Sonarcloud"
             curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
-          else
-            echo "Proyecto ya creado en Sonarcloud o error detectado durante la creación"
           fi
       - name: Validating project type
+        id: validate-project-type
         run: |
         
-          if [ -f "package.json" ]; then
+          if [ -f "package.json " ]; then
             echo "Proyecto Node.js"
-            echo "project_type=node.js" >> $GITHUB_ENV
-            
+            echo "NODEJS=true" >> $GITHUB_ENV
           else
             echo "Tipo de proyecto no soportado"
             exit 1
